### PR TITLE
Fixed Navbar centering & search input/button styling

### LINKED ISSUE #135: BUG: NavBar and Search field UI Bugs
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The nav items are not in the center of the nav section.
nav

Search icons is not properly aligned with the search input field, it is supposed to be on left side inside the search
sbar
searchbar

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by The-Phoenics**
### Description
A clear and concise description of what the PR does.
- This PR does the following:
  - Fixes NavBar (previously sidebar) and search button and search input in Navbar
  - Updates Sidebar, making it responsive and fixes search field.

### Related Issues
Fixes #135

### Changes
List the detailed changes made in this PR.
- Added new icons as svg components in newly created Assets folder
- Refactored unnecessary styling in App.css with new changes.

### Screenshots (if applicable)
large_screen
medium
small_screensize

### Checklist
Make sure to check off all the items before submitting. Mark with [x] if done.
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I am working on this issue under GSSOC

### CODE REVIEW

**Comment by The-Phoenics** [comment]
Hi @Satyam1923,
I've made necessary changes to the **NavBar** and search fields. Can you review my PR.

**Comment by saurabhsingh720** [comment]
@The-Phoenics 
Can u give a preview of the changes in video format.
Make suru in every device screen view the responsiveness never affect.

**Comment by The-Phoenics** [comment]
Here is the video:

Uploading navbar_fix_video.mp4…

@saurabhsingh720

**Comment by The-Phoenics** [comment]
Here's the video @saurabhsingh720,
https://github.com/Satyam1923/Spring-Music-Player/assets/96228962/47836e05-6413-4bc6-8fbc-c454780217bd

**Comment by saurabhsingh720** [comment]
> Here's the video @saurabhsingh720, https://github.com/Satyam1923/Spring-Music-Player/assets/96228962/47836e05-6413-4bc6-8fbc-c454780217bd

Text is overflowing

**Comment by The-Phoenics** [comment]
> > Here's the video @saurabhsingh720, https://github.com/Satyam1923/Spring-Music-Player/assets/96228962/47836e05-6413-4bc6-8fbc-c454780217bd
> 
> Text is overflowing 

Text within centre and the right section of page?

**Comment by The-Phoenics** [comment]
Hey  @Satyam1923,

I haven't received any response on this PR; it's been more than a week now. Could you merge this PR until the new design is ready, or if it's not valid, could we close it?

**Pull request closed without merging**
