### PR TITLE
artist particualr pagw with their songs

### LINKED ISSUE #448: Feat: Design Artist Page
### Describe the feature

@Satyam1923 

we can design `/artist/:id` page for particular artist page

### Add ScreenShots

image

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by dhruv8433**
@Satyam1923 
@saurabhsingh720 

Feat: Design Artist Page #448

close #448

### Description
A clear and concise description of what the PR does.
- This PR does the following:
  - Adds `artist/:id` page for particular artists
  - Fixes ...
  - Updates ...

### Related Issues
Link any related issues using the format `Fixes #issue_number`. 
This helps to automatically close related issues when the PR is merged.
- Placeholder: "Fixes #448"

### Changes
List the detailed changes made in this PR.
- Added a new feature to ...
- Refactored the ...
- Fixed a bug in ...

### Testing Instructions
Detailed instructions on how to test the changes. Include any setup needed and specific test cases.
1. Pull this branch.
2. Run `npm install` to install dependencies.
3. go to search page
4. try to click on partricular artist's 

### Screenshots (if applicable)
Add any screenshots that help explain or visualize the changes.

https://github.com/Satyam1923/Spring-Music-Player/assets/114583978/5ddfcb18-390c-481f-88bf-355dd96e80e1

### Additional Context
Any additional context or information that reviewers should be aware of.
- This PR is based on the following...

### Checklist
Make sure to check off all the items before submitting. Mark with [x] if done.
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I am working on this issue under GSSOC

### CODE REVIEW

**Comment by dhruv8433** [comment]
@Satyam1923 

please add level and merge it

**Comment by Satyam1923** [comment]
@dhruv8433 add play functionality also for songs.

**Comment by dhruv8433** [comment]
@Satyam1923 

now you can check that, 
when user select any particular song from artist page it played 

image

please add level as per my work ...

**Comment by dhruv8433** [comment]
@Satyam1923

now you can check that,
when user select any particular song from artist page it played
please add level as per my work ...

**Comment by Satyam1923** [comment]
Screenshot 2024-07-05 171518
reduce size of artist name and add a scrollbar for all songs it's going below the page.

**Comment by dhruv8433** [comment]
@Satyam1923 

- update artist name size
- add vertical scroll bar 

image

**Comment by dhruv8433** [comment]
@Satyam1923

update artist name size
add vertical scroll bar

kindly please check this and merge it
also add level 3

**Comment by dhruv8433** [comment]
@Satyam1923

update artist name size
add vertical scroll bar

kindly please check this and merge it
also add level 3

**Comment by dhruv8433** [comment]
@Satyam1923

update artist name size
add vertical scroll bar

kindly please check this and merge it
also add level 3

**Comment by dhruv8433** [comment]
@Satyam1923

update artist name size
add vertical scroll bar

kindly please check this and merge it
also add level 3

**Pull request merged**
