### PR TITLE
Feat: 404 not found page added with config #216

### PR DESCRIPTION
**Pull request by RamakrushnaBiswal**
### Description
A clear and concise description of what the PR does.
- This PR does the following:
  - Adds ... a 404.png image,PagenotFound.jsx and its CSS file
  - Fixes ... add the pages 
  - Updates ...

### Related Issues
issue #216 
Link any related issues using the format `Fixes #issue_number`. 
This helps to automatically close related issues when the PR is merged.
- Placeholder: "Fixes #123"

### Changes
List the detailed changes made in this PR.
- Added a new feature to ...
- Refactored the ...
- Fixed a bug in ...

### Testing Instructions
Detailed instructions on how to test the changes. Include any setup needed and specific test cases.
1. Pull this branch.
2. Run `npm install` to install dependencies.
3. Run `npm test` to execute the test suite.
4. Verify that ...

### Screenshots (if applicable)

https://github.com/Satyam1923/Spring-Music-Player/assets/125277258/ef12b238-e8c6-4919-ba46-c4f4de52945e

### Additional Context
Any additional context or information that reviewers should be aware of.
- This PR is based on the following...

### Checklist
Make sure to check off all the items before submitting. Mark with [x] if done.
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I am working on this issue under GSSOC

### CODE REVIEW

**Comment by RamakrushnaBiswal** [comment]
@Satyam1923 please review the PR

**Comment by RamakrushnaBiswal** [comment]
hi @Satyam1923 here it is working
here i add a invalid URL it works
image

**Comment by Satyam1923** [comment]
@RamakrushnaBiswal fine.

**Comment by RamakrushnaBiswal** [comment]
Thank you sir @Satyam1923

**Pull request merged**
