### PR TITLE
Resolving issue Feat:Adding more css to background #336

### PR DESCRIPTION
**Pull request by Garima-149**
Screenshot (57)
@Satyam1923 Please check it once.If it is ok,then please merge it.

### CODE REVIEW

**Comment by Satyam1923** [comment]
@Garima-149 please don't do this hit even if it was deployed I would have removed this PR.

**Comment by Garima-149** [comment]
@Satyam1923  Would you please tell what wrong did I do? That you have closed it without merging.

**Comment by Satyam1923** [comment]
@Satyam1923 first of all due check current design of about us page whats wrong in that why event change that design it was someone's else contribution.
mention issues before raising pr.
don't use copyright resources.

**Comment by Satyam1923** [comment]
@Garima-149  Before raising a pull request, it's important to review the current design of the "About Us" page and identify any issues. It's also crucial to ensure that any changes made do not include copyrighted resources and to maintain correct grammar throughout the content. If the current design was contributed by someone else, it's essential to respect their contributions and only make changes that improve the overall user experience or address specific issues.

**Comment by Garima-149** [comment]
@Satyam1923  Ok I am sorry. I understood. Should I make changes again in about. Js page and ensure to get review  from your side?

**Pull request closed without merging**
