### PR TITLE
Added the language dropdown feature in the updated branch

### PR DESCRIPTION
**Pull request by Riddhi162**
This PR adds the optioon to filter songs based on the language.

Fixed https://github.com/Satyam1923/Spring-Music-Player/issues/112 issue

So this works something like this first the user can write the name of the song and then from the language dropdown he/she can select the language of it so filtering is preformed in this way.
And if for that particular song there is no language available it displays no data found

image

https://github.com/Satyam1923/Spring-Music-Player/assets/135015856/11ac5a45-fd52-4bef-9d80-7109b76478cf

### Checklist
Make sure to check off all the items before submitting. Mark with [x] if done.
[ x] I have performed a self-review of my code
[x ] I have commented my code, particularly in hard-to-understand areas
[x ] My changes generate no new warnings
[x ] I am working on this issue under GSSOC

### CODE REVIEW

**Comment by saurabhsingh720** [comment]
@Riddhi162 
Add the artist section that u have removed

**Comment by Riddhi162** [comment]
> @Riddhi162 Add the artist section that u have removed

from where?

**Comment by saurabhsingh720** [comment]
@Riddhi162 
Screenshot_2024-05-25-15-49-48-35_40deb401b9ffe8e1df2f1cc5ba480b12

**Comment by saurabhsingh720** [comment]
@Riddhi162

**Comment by saurabhsingh720** [comment]
@Riddhi162 

Initially 
Screenshot_2024-05-25-20-32-27-46_40deb401b9ffe8e1df2f1cc5ba480b12

After your changes

**Comment by Riddhi162** [comment]
sorry but i am unable to see the last screenshot

**Comment by Riddhi162** [comment]
Hello can i know if this work of mine is considered or not. Pls consider it.
@Satyam1923

**Comment by Satyam1923** [comment]
it should be considered.

**Pull request merged**
