### PR TITLE
issue #205

### LINKED ISSUE #205: Feat: Redesigning the whole website according to the figma template given
### Describe the feature

I will Redesign the whole website as per the Figma template given in Readme file

also would fix some small bugs ,validations, and overall User experience of the website

please assign me this issue so that i could get an assurance from the owner to start the work.

### Add ScreenShots

the figma link:
https://www.figma.com/design/WQnt0qRFSdaV3jW5XF8NSc/Spring-Music-player-new-design

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Yash-Ainapure**
### Description
- This PR does the following:
  - Fixes the song not playing
  - Fixes Top Artists list displayed 
  - Fixes the API problem where the search feature wasn't working
  - Updates basic UI (further UI as per Figma FIle will me made in further PR's)
- Updates effect
  - now you can search for any song and get the list of songs and can play it on clicking it.
  - see the top songs list,it can also be played on clicking on it

### Related Issues
- Fixes #205

### Screenshots
image

### Checklist
Make sure to check off all the items before submitting. Mark with [x] if done.
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I am working on this issue under GSSOC

### CODE REVIEW

**Comment by Yash-Ainapure** [comment]
@Satyam1923  I have made the website come in working successfully.
merge it now ,then we will be working on the UI part as per the figma file.
Also suggest any things that to be made in further PR's

**Comment by Satyam1923** [comment]
@Yash-Ainapure why images quality is blurish. Rest seems fine.

**Comment by Yash-Ainapure** [comment]
> @Yash-Ainapure why images quality is blurish. Rest seems fine.

Really don't know why. I haven't applied any styling to it.  Increasing the width and height of it, will make it clear I think

**Comment by Yash-Ainapure** [comment]
@Satyam1923 , so will you merge it now or anything else i have to do? 
Thanks you

**Comment by Satyam1923** [comment]
@Yash-Ainapure rest everything seems fine just look into that blurry images and if possible remove those gifs in starting.

**Comment by Yash-Ainapure** [comment]
> @Yash-Ainapure rest everything seems fine just look into that blurry images and if possible remove those gifs in starting.


- improved image quality
- removed those gifs

**Comment by Satyam1923** [comment]
@Yash-Ainapure 
Screenshot 2024-05-30 114436
Still this gif is intact there and whenever we click on top artist media players goes behind choose song to play ui.

**Comment by Yash-Ainapure** [comment]
> @Yash-Ainapure Screenshot 2024-05-30 114436 Still this gif is intact there and whenever we click on top artist media players goes behind choose song to play ui.



> @Yash-Ainapure Screenshot 2024-05-30 114436 Still this gif is intact there and whenever we click on top artist media players goes behind choose song to play ui.

Ok will fix that till tonight

**Comment by Yash-Ainapure** [comment]
> @Yash-Ainapure Screenshot 2024-05-30 114436 Still this gif is intact there and whenever we click on top artist media players goes behind choose song to play ui.



> @Yash-Ainapure Screenshot 2024-05-30 114436 Still this gif is intact there and whenever we click on top artist media players goes behind choose song to play ui.

Ok will fic that till tonight

**Comment by Yash-Ainapure** [comment]
@Satyam1923 .
I think it's correct now.
I have removed the div unless we play any song(search field song OR Top suggested song)

**Pull request merged**
