### PR TITLE
Fixed the search results stylings

### PR DESCRIPTION
**Pull request by Yash-Ainapure**
now it looks like this

image

### CODE REVIEW

**Comment by Yash-Ainapure** [comment]
@Satyam1923 ,

Could you mark this PR as level 2? 🥲

**Comment by Satyam1923** [comment]
No, don't create issue and fix them by yourself.

**Comment by Yash-Ainapure** [comment]
> No, don't create issue and fix them by yourself. I'll not label it under gssoc.

I have not created it, It was just my mistake.
while testing I didn't test the UI for after Searching for a song, that's why it was left as a bug

**Comment by Yash-Ainapure** [comment]
@Satyam1923 , So can i get gssoc points for it? 
I haven't tried to create issue and fix by myself, what about the other 600 lines of css code that i removed from the codebase while solving that issue. 
It was left by mistake

**Comment by Satyam1923** [comment]
@Yash-Ainapure don't worry about the points for I'll just mark it for level 0 .

**Pull request merged**
