### PR TITLE
Implemented new search all page design

### LINKED ISSUE #256: Feat: Implement All Search page
### Describe the feature

I would like to work on implementing the all search page from the new design.

### Add ScreenShots

all-search-page

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by The-Phoenics**
### Description
Implemented the new design of the search-all page.

### Related Issues
- Placeholder: "Fixes #256 "

### Changes
List the detailed changes made in this PR.
- Added a new feature to `Search.jsx`
- Refactored the `App.jsx`

### Screenshots
search-all-page

### Checklist
Make sure to check off all the items before submitting. Mark with [x] if done.
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I am working on this issue under GSSOC

### CODE REVIEW

**Comment by The-Phoenics** [comment]
Hey @Satyam1923 
I've implemented the search-all page. I've also did some workaround for navigation. So now we can navigate to home and search page back and forth via navbar `home` and `search` button.
Can you please review the PR?

**Comment by The-Phoenics** [comment]
Hey @Satyam1923 
By this `"and at least make search page songs functional"`
did you mean hardcode the songs in this section and make them playable?
songs-play

**Comment by Satyam1923** [comment]
@The-Phoenics ya this one.

**Comment by The-Phoenics** [comment]
Hey @Satyam1923 
Can you check it now the songs in songs list and top songs list are getting fetched from the api and working properly.

**Comment by Satyam1923** [comment]
Screenshot from 2024-06-09 17-23-51
m
Screenshot from 2024-06-09 17-24-03
make that search bar functional and also side bar is not expanding in search page.

**Comment by Satyam1923** [comment]
https://github.com/Satyam1923/Spring-Music-Player/assets/104068640/abe6b326-f88f-475d-b6f6-4673b0078381
this one for side bar.

**Comment by Satyam1923** [comment]
https://github.com/Satyam1923/Spring-Music-Player/assets/104068640/43170e36-4da2-4c5e-9f7b-175f93b59bdf

this one for search bar.

**Comment by Satyam1923** [comment]
@The-Phoenics fine seems good thank you for you effort now just make the routers and remove the old page.

**Comment by Satyam1923** [comment]
@The-Phoenics mm whenever we click on search icon it's start playing marry on a cross? can you fix it.

**Comment by The-Phoenics** [comment]
Hey @Satyam1923 
I've removed autoplay. Can you please check again?

**Comment by Satyam1923** [comment]
@The-Phoenics still same it starts playing marry on a cross on click on search button.

**Comment by The-Phoenics** [comment]
@Satyam1923 Can you please check again?

**Comment by Satyam1923** [comment]
@The-Phoenics ya check it same issue.

**Comment by The-Phoenics** [comment]
@Satyam1923 Can you check again now?

**Comment by Satyam1923** [comment]
@The-Phoenics now for every song we have to click on play button whenever we choose from list.

**Comment by The-Phoenics** [comment]
@Satyam1923 Can you check once again?

**Comment by Satyam1923** [comment]
@The-Phoenics Fine now it's working, but wait a little someone is making auth page so he needs to change app.jsx and If i accept you PR then it raises issues.

**Comment by Satyam1923** [comment]
@The-Phoenics could resolve these conflicts I'll merge your PR then.

**Comment by Satyam1923** [comment]
Screenshot 2024-06-10 192259
All these section are not working now.

**Comment by The-Phoenics** [comment]
@Satyam1923 Can you check again?

**Pull request merged**
