### PR TITLE
Feat: #94 complete Search Page Component

### LINKED ISSUE #94: Feat: Create Search Page Component
### Describe the feature

i see the figma design i can see their an search result page and i think i can make this design 
please assign this feature , i want to work on this 

### Add ScreenShots

image

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by CoderSwarup**
close #94 

completed the Search result page as per ui requirement 

Additionally implement The Features As 
- Responsive 
- Search Song 
- play song 
- Pause song 

here is the Video  for reference [Video](https://fileport.io/ZK3WFC2N7K2t)

also Additionally their is an No navigation apply on the react to switch the different page check this issue #105 that i purpose 

to navigate search page 
use `/search`
or their is button on the home page to navigate 

i am waiting for your feedback Thanks

### CODE REVIEW

**Comment by Satyam1923** [comment]
I don't know the reason for now but hitting the bottom shows this error. I'll check the code after some time.

**Comment by CoderSwarup** [comment]
> 
> 
> I don't know the reason for now but hitting the button shows this error. I'll check the code after some time.

Before directly check on the Deployed app please check on the local development mode

**Comment by CoderSwarup** [comment]
@Satyam1923 any update

**Comment by CoderSwarup** [comment]
@Satyam1923 hi any update from your side

**Pull request closed without merging**
