### PR TITLE
Resolving issue no.#366

### PR DESCRIPTION
**Pull request by Garima-149**
My first Pr was abruptly closed by github-actions because of your inactivity.This PR has merging conflicts.Please tell me how to solve this. @Satyam1923

### CODE REVIEW

**Comment by Satyam1923** [comment]
Screenshot 2024-07-12 005508
fix these errors

**Comment by Satyam1923** [comment]
@Garima-149 i am not inactive just have others work in my own life.

**Comment by Garima-149** [comment]
@Satyam1923  Ok But I am not saying this. This was the reason that github actions closed it automatically.

**Review by Garima-149 — COMMENTED** [review]
Tried to resolved it.

**Comment by Satyam1923** [comment]
@Garima-149 could you mention issue number.

**Pull request merged**
