### PR TITLE
[Feature] : Add search & song

### PR DESCRIPTION
**Pull request by sivaprasath2004**
- I will finish the solution.
- use for `useEffect` hook and check the `searchResult` and filter the result and set it.

### Preview Video
[Screencast from 2024-05-13 08-01-52.webm](https://github.com/Satyam1923/Spring-Music-Player/assets/121082414/d0ec09cd-ce9f-47e5-80a4-ed866d0e0287)

### CODE REVIEW

**Comment by sivaprasath2004** [comment]
@Satyam1923 i will finish and `App.jsx` to write  the codes that is work in proper. please merge it and rock it.

**Review by Satyam1923 — COMMENTED** [review]
Check the deploy vercel app it's crashing too much and searching saware song without entry.

**Comment by sivaprasath2004** [comment]
@Satyam1923 please remove the following code in `master` branch that is not needed....
- In `App.jsx`  remove the code `6 line`
```bash
import he from "he";
```
### master branch
Screenshot from 2024-05-13 20-59-50
### change to 
Screenshot from 2024-05-13 21-05-09

- I'm sure it is work please change it.....

**Comment by sivaprasath2004** [comment]
- If reference my code in github [https://github.com/sivaprasath2004/Spring-Music-Player/blob/master/frontend/src/App.jsx](https://github.com/sivaprasath2004/Spring-Music-Player/blob/master/frontend/src/App.jsx)  copy the file and paste to the `main` branch `App.jsx` file and resolve the conflicts.

**Comment by Satyam1923** [comment]
If reference my code in github https://github.com/sivaprasath2004/Spring-Music-Player/blob/master/frontend/src/App.jsx copy the file and paste to the main branch App.jsx file and resolve the conflicts.

Time to close this PR because you want me to copy paste the code.

**Pull request closed without merging**
