### PR TITLE
Solving issue Feat:container box and text is overriding #366

### PR DESCRIPTION
**Pull request by Garima-149**
Please merge it @Satyam1923

### CODE REVIEW

**Comment by Satyam1923** [comment]
@Garima-149 build failed.

**Comment by Satyam1923** [comment]
@Garima-149 errors.

**Comment by Garima-149** [comment]
@Satyam1923 please tell how can I solve these errors? I have tried to check on vercel too but unable to find anything that could help me.

**Comment by Garima-149** [comment]
@Satyam1923 The link you provided is not opening

**Pull request closed without merging**
