### PR TITLE
Added nested routes for search filter

### LINKED ISSUE #322: Feat: Setup nested routes for Search page
### Describe the feature

Search components has many routed child components. So, the nested routes must be added using `react-router-dom`'s Outlet feature.

### Add ScreenShots

search

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by The-Phoenics**
### Description
- This PR adds nested routes for search page search filter

### Related Issues
- Placeholder: "Fixes #322 "

### Testing Instructions
Detailed instructions on how to test the changes. Include any setup needed and specific test cases.
1. Pull this branch.
2. Run `npm install` to install dependencies.
3. Run `npm test` to execute the test suite.

### Checklist
Make sure to check off all the items before submitting. Mark with [x] if done.
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I am working on this issue under GSSOC

### CODE REVIEW

**Comment by Satyam1923** [comment]
@The-Phoenics could please wait let me add something good in search page then I'll see if your branch is mergeable.

**Comment by The-Phoenics** [comment]
Sure @Satyam1923

**Comment by The-Phoenics** [comment]
Can you please check if there are any issues @Satyam1923 ?

**Comment by Satyam1923** [comment]
Screenshot 2024-06-18 123837
deployment error.

**Comment by Satyam1923** [comment]
@The-Phoenics what I was thinking that we don't need different pages for search page. We can just keep a filter state for songs/artists page then use that state to configure hitting different end points and changing the elements according to it.

**Comment by Satyam1923** [comment]
@The-Phoenics deployment fail.

**Comment by The-Phoenics** [comment]
@Satyam1923 its working on my system 🤔
Can you share the deployment errors?

working

**Comment by The-Phoenics** [comment]
@Satyam1923 Can you please check once again?

**Comment by The-Phoenics** [comment]
Hey @Satyam1923 
Can you please add the GSSoC'24 labels!

**Pull request merged**
