### PR TITLE
Added the Login and Sign-Up functionality

### LINKED ISSUE #207: Feat: Adding the Login and Sign-Up functionality
### Describe the feature

I'm interested in contributing to the project by adding the login and sign-up functionality. 

Could you please assign this task to me under GSSoC with appropriate level?

### Add ScreenShots

image
image

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by ParthNakum21**
Updated Sign-Up Screen and Login Screen for better visibility and to maintain a consistent theme across all pages. Fixed #207

### CODE REVIEW

**Comment by Satyam1923** [comment]
@ParthNakum21 make an endpoint or button to test / debug login ui.

**Comment by ParthNakum21** [comment]
> @ParthNakum21 make an endpoint or button to test / debug login ui. I gave level 3 to this issue because I wanted you to actually build login functionality with firebase.

I am working on that part. 
Please let me know if you need any changes in the UI.

**Comment by Satyam1923** [comment]
@ParthNakum21 not working just showing heading login / signup

**Comment by Satyam1923** [comment]
@ParthNakum21 so I tell you what someone has already prepared the login functionality and his own design . You prepare the design provided in figma and then I'll merge your PR.

**Comment by ParthNakum21** [comment]
> @ParthNakum21 so I tell you what someone has already prepared the login functionality and his own design . You prepare the design provided in figma and then I'll merge your PR.

Hello @Satyam1923, I have designed the login and signup page in a way that it maintains a consistent theme across all pages.
We had discussed this in #207 conversation. 
I have committed the changes. Please review it now.

**Comment by ParthNakum21** [comment]
> > @ParthNakum21 so I tell you what someone has already prepared the login functionality and his own design . You prepare the design provided in figma and then I'll merge your PR.
> 
> Hello @Satyam1923, I have designed the login and signup page in a way that it maintains a consistent theme across all pages. We had discussed this in #207 conversation. I have committed the changes. Please review it now.

@Satyam1923, Please review it and let me know if you need any changes.

**Comment by Satyam1923** [comment]
@ParthNakum21 then also make the figma design file and send me the link. So I can make changes in design.

**Comment by ParthNakum21** [comment]
> @ParthNakum21 then also make the figma design file and send me the link. So I can make changes in design.

@Satyam1923, Please review the figma design.

Figma Link: https://www.figma.com/design/sHFX3Co5mbKeQwixHYoh5A/Untitled?node-id=0-1&t=bo2P7o60lUjHQq7z-1

**Comment by Satyam1923** [comment]
@ParthNakum21 Don't you think current one look better than this.

**Comment by ParthNakum21** [comment]
> @ParthNakum21 Don't you think current one look better than this.

No worries, I will design that.

**Pull request closed without merging**
