### PR TITLE
Album page

### LINKED ISSUE #298: Feat: Create Album ui
### Describe the feature

@Satyam1923 

we can create album ui something like this

### Add ScreenShots

image

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by dhruv8433**
### Description

@Satyam1923 

Feat: Create Album ui #298

close #298

A clear and concise description of what the PR does.
- This PR does the following:
  - Adds new route `/album/:id`
  - Fixes ...
  - Updates ...

### Related Issues
Link any related issues using the format `Fixes #issue_number`. 
This helps to automatically close related issues when the PR is merged.
- Placeholder: "Fixes #298"

### Changes
List the detailed changes made in this PR.
- Added a new feature to album card
- when user click on any artist they will redirected to album page of that artist

### Testing Instructions
Detailed instructions on how to test the changes. Include any setup needed and specific test cases.
1. Pull this branch.
2. Run `npm install` to install dependencies.
3. Run `npm test` to execute the test suite.
4. Verify that ...

### Screenshots (if applicable)
Add any screenshots that help explain or visualize the changes.

https://github.com/Satyam1923/Spring-Music-Player/assets/114583978/1ac9dc71-a239-4f02-adba-25ae4c31a62d

### Additional Context
Any additional context or information that reviewers should be aware of.
- This PR is based on the following...

### Checklist
Make sure to check off all the items before submitting. Mark with [x] if done.
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I am working on this issue under GSSOC

### CODE REVIEW

**Comment by dhruv8433** [comment]
@Satyam1923 

kindly please check this and merge it
if you want any modifications, please inform me

**Comment by Satyam1923** [comment]
@dhruv8433 at what endpoint should I test it out.

**Comment by dhruv8433** [comment]
@Satyam1923 

try to click on any artist card it will redirect you to `/artist/:id`

**Comment by Satyam1923** [comment]
Screenshot 2024-06-24 133512
still need a lot of work album name songs etc. and reduce the size of it media player's size is reduced.

**Comment by dhruv8433** [comment]
@Satyam1923 

ok so i have to fetch real time songs based on artist right...?

**Comment by Satyam1923** [comment]
Yess..

**Comment by dhruv8433** [comment]
@Satyam1923 

i called top song api in album page
now you check this and merge it

image

**Comment by dhruv8433** [comment]
@Satyam1923 

please inform me if you want any modifications

**Comment by Satyam1923** [comment]
@dhruv8433 what are  you doing and it's album page issue why work under artists. and album should be open when we click on some particular album in search page. Don't make any  changes in home page.

**Comment by dhruv8433** [comment]
@Satyam1923 

now you can merge it

https://github.com/Satyam1923/Spring-Music-Player/assets/114583978/54c7788e-29d2-4c21-856a-ca7aaff8fd3d

**Comment by dhruv8433** [comment]
@Satyam1923 

kindly please check this and merge it

**Comment by dhruv8433** [comment]
@Satyam1923 

i update my code and now you can check this
it fetch song by their album name

please inform me if you need any modifications

image

image

**Comment by Satyam1923** [comment]
Screenshot 2024-06-26 000616
bug

**Comment by Satyam1923** [comment]
Screenshot 2024-06-26 000637
it should contain all the songs right?

**Comment by dhruv8433** [comment]
Yes

**Comment by dhruv8433** [comment]
@Satyam1923 

I display all songs from album

**Comment by dhruv8433** [comment]
@Satyam1923 

i resolved zoom bug and all album have only one song so i display it 
kindly please check this and merge it

image

**Comment by Satyam1923** [comment]
@dhruv8433 I guess I have to try to write every thing for you in search there is already a section for only albums search and take id of albums search with albums id you will get all the songs. Do I have to right every single details everytime?

**Comment by dhruv8433** [comment]
@Satyam1923 

image

image

**Comment by Satyam1923** [comment]
@dhruv84 there should be all the songs concerning to particular albums right?

**Comment by dhruv8433** [comment]
@Satyam1923 

Yes, all album songs

**Comment by Satyam1923** [comment]
Screenshot 2024-06-29 225725
increase the size of music payer like others player rest is fine.

**Comment by dhruv8433** [comment]
@Satyam1923 

as you mention, i update the size of music player

image

**Pull request merged**
