### PR TITLE
Added the contributors page

### LINKED ISSUE #461: Feat: Add Contributors Page to Display Project Contributors
### Describe the feature

The contributors page will display the details of the contributors who have contributed to this project

### Add ScreenShots

04 07 2024_14 29 42_REC
Will add it in the footer 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by pani2004**
"Fixes #461 "

- [ x] I have performed a self-review of my code
- [ x] My changes generate no new warnings
- [ x] I am working on this issue under GSSOC

https://github.com/Satyam1923/Spring-Music-Player/assets/154724111/1d35222a-5b72-4e4a-80fe-b048e008801e

### CODE REVIEW

**Comment by pani2004** [comment]
@Satyam1923 Pls review this PR!!!

**Comment by Satyam1923** [comment]
Screenshot 2024-07-06 035828
change white to grayish like other ui elements.

**Comment by pani2004** [comment]
okk

**Comment by pani2004** [comment]
@Satyam1923 Check now and can I get level2 for this?

**Pull request merged**
