### PR TITLE
Adds SignUp button in the homepage

### LINKED ISSUE #384: Feat: Adding a SignUp button at the top-gnear the Sin
### Describe the feature

Place a prominently styled signup button at the top right corner of the homepage and main screens, using contrasting colors, rounded corners, and hover effects for visibility. Implement the button in HTML and CSS with responsive design adjustments for smaller screens. Add JavaScript to redirect users to the signup page upon clicking the button. This setup ensures the button is appealing, functional, and responsive.

### Add ScreenShots

Screenshot 2024-06-17 at 11 26 23 AM
Screenshot 2024-06-17 at 11 24 48 AM

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by arunimaChintu**
### Description
A clear and concise description of what the PR does.
- This PR does the following:
  - Adds Sign Up Button in the Home page ...
  - Fixes #384 ...
  - Updates ...

### Related Issues
Link any related issues using the format `Fixes #issue_number`. 
This helps to automatically close related issues when the PR is merged.
- Placeholder: "Fixes #384"

### Changes
List the detailed changes made in this PR.
- Added a new feature to ...
- Refactored the ...
- Fixed a bug in ...

### Testing Instructions
Detailed instructions on how to test the changes. Include any setup needed and specific test cases.
1. Pull this branch.
2. Run `npm install` to install dependencies.
3. Run `npm test` to execute the test suite.
4. Verify that ...

### Screenshots (if applicable)
Add any screenshots that help explain or visualize the changes.

### Additional Context
Any additional context or information that reviewers should be aware of.
- This PR is based on the following...

### Checklist
Make sure to check off all the items before submitting. Mark with [x] if done.
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I am working on this issue under GSSOC

### CODE REVIEW

**Comment by Satyam1923** [comment]
@arunimaChintu adjust its position ?

**Comment by arunimaChintu** [comment]
@Satyam1923 yes it does adjust the position of the sign-up button. Heres the relevent part of the code: "<div className="fixed bottom-4 right-4">
  <button
    onClick={handleSignUp}
    className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline"
  >
    Sign Up
  </button>
</div>
"

**Comment by arunimaChintu** [comment]
Yes it does adjusts its position. Heres the relevent part of the code:
<div className="fixed bottom-4 right-4">
  <button
    onClick={handleSignUp}
    className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline"
  >
    Sign Up
  </button>
</div>

**Comment by Satyam1923** [comment]
@arunimaChintu no just fix it besides login button.

**Comment by arunimaChintu** [comment]
okay!

**Pull request closed without merging**
