### PR TITLE
Added Backgroud Image 

### PR DESCRIPTION
**Pull request by SadafKausar2025**

### CODE REVIEW

**Comment by SadafKausar2025** [comment]
I dont't know why I am unable to see the search icon or SVG in the page

**Comment by SadafKausar2025** [comment]
fixed the issue number #84

**Comment by SadafKausar2025** [comment]
Screenshot (1701)

**Review by Satyam1923 — COMMENTED** [review]
There are some procedure that you need to follow according to gssoc if you want points.
Secondly raise issues then send Pr.
Thirdly check design before raising issue.

**Pull request closed without merging**
