### PR TITLE
Changing as instructed

### PR DESCRIPTION
**Pull request by Sibam-Paul**
Did changes #64

### CODE REVIEW

**Comment by Satyam1923** [comment]
fine!

**Comment by Sibam-Paul** [comment]
can u please level it 'level1' as it won't be counted in leaderboard and please note l must be small and no space

**Comment by Sibam-Paul** [comment]
@Satyam1923

**Comment by Sibam-Paul** [comment]
@Satyam1923 Please give ' level1 ' to this
see
image

**Pull request merged**
