### PR TITLE
Figma template UI 2nd version

### PR DESCRIPTION
**Pull request by Yash-Ainapure**
### Description
Made a 2nd version of Spotify Interface

### Related Issues
#222 

### Changes
- Added new stylings
- Added Top artists component
- Made some css fixes

### Screenshots
image

This is the present version Interface

### Checklist
Make sure to check off all the items before submitting. Mark with [x] if done.
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I am working on this issue under GSSOC

### CODE REVIEW

**Comment by Yash-Ainapure** [comment]
@Satyam1923 
### after resolving merge conflicts the UI now looks like:
image

**Comment by Yash-Ainapure** [comment]
@Satyam1923 ,could you please review it?

**Comment by Satyam1923** [comment]
seems good now.

**Comment by Satyam1923** [comment]
Screenshot 2024-06-03 201735
for now raise the player ui a little bit.

**Comment by Yash-Ainapure** [comment]
> Screenshot 2024-06-03 201735 for now raise the player ui a little bit.

@Satyam1923 ,now you can check it

**Pull request merged**
