### PR TITLE
Designing Login, Signup page and User Profile page in Figma #21

### LINKED ISSUE #21: Designing Login, Signup page and User Profile page in Figma
**Is your feature request related to a problem? Please describe.**
As Developer need Figma file to achieve rapid development, It's necessary to design Figma Prototype

**Describe the solution you'd like**
I would like to add corresponding page designs in Figma

### PR DESCRIPTION
**Pull request by Prithwi32**
### Description
A clear and concise description of what the PR does.
- This PR does the following:
  - Adds ...
 Login, SignUp page designing in figma

### Related Issues
Link any related issues using the format `Fixes #issue_number`. 
This helps to automatically close related issues when the PR is merged.
- Placeholder: "Fixes #21"

### Changes
List the detailed changes made in this PR.
- Added a new designs in figma

### Testing Instructions
Detailed instructions on how to test the changes. Include any setup needed and specific test cases.
1. Pull this branch.
2. Run `npm install` to install dependencies.
3. Run `npm test` to execute the test suite.
4. Verify that ...

### Screenshots (if applicable)
image
image

### Additional Context
Any additional context or information that reviewers should be aware of.
- This PR is based on the following...

### Checklist
Make sure to check off all the items before submitting. Mark with [x] if done.
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I am working on this issue under GSSOC

### CODE REVIEW

**Comment by Prithwi32** [comment]
@Satyam1923 as you know I worked on initial  Figma File...done login, SignUp pages and Home screen..now new design came we know..as a part of my previous assigned work made this PR..
let me know It was okay
and any other design I can add in new figma file

**Comment by Satyam1923** [comment]
??

**Comment by Prithwi32** [comment]
> ??
@Satyam1923 
I asked what else should i work?

**Comment by Satyam1923** [comment]
just remove the file change and I'll accept this PR>.

**Comment by Prithwi32** [comment]
@Satyam1923 could you check once now

**Pull request merged**
