### PR TITLE
Liked song page

### LINKED ISSUE #293: Feat: We can create seperate liked song pages
### Describe the feature

@Satyam1923 

we can create seperate liked music page when user click on that they will redirected to `/liked-song`

### Add ScreenShots

image

something like this

image

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by dhruv8433**
### Description

Feat: We can create seperate liked song pages #293

A clear and concise description of what the PR does.
- This PR does the following:
  - Adds Liked Song Page
  - Fixes  #293
  - Updates slidebar and add new route `/liked-song`

### Related Issues
Link any related issues using the format `Fixes #issue_number`. 
This helps to automatically close related issues when the PR is merged.
- Placeholder: "Fixes #123"

### Changes
List the detailed changes made in this PR.
- Added a new feature to `liked song`
- Refactored the slidebar
- Fixed a bug in #293

### Testing Instructions
Detailed instructions on how to test the changes. Include any setup needed and specific test cases.
1. Pull this branch.
2. Run `npm install` to install dependencies.
3. Run `npm test` to execute the test suite.
4. Verify that ...

### Screenshots (if applicable)
Add any screenshots that help explain or visualize the changes.

https://github.com/Satyam1923/Spring-Music-Player/assets/114583978/656feb6f-8d32-464f-a386-095c0e462923

### Additional Context
Any additional context or information that reviewers should be aware of.
- This PR is based on the following...

### Checklist
Make sure to check off all the items before submitting. Mark with [x] if done.
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I am working on this issue under GSSOC

### CODE REVIEW

**Comment by dhruv8433** [comment]
@Satyam1923 

kindly please check this and merge it

**Comment by Satyam1923** [comment]
@dhruv8433 how should I test it out and using main page music player card.

**Comment by dhruv8433** [comment]
@Satyam1923 

clikc on  liked icon in slide
image

**Comment by Satyam1923** [comment]
@dhruv8433 check deployed version it's not working.

**Comment by dhruv8433** [comment]
i can't have access of deployed version

basically i created ui for liked song

**Comment by dhruv8433** [comment]
@Satyam1923 


https://github.com/Satyam1923/Spring-Music-Player/assets/114583978/b223efdd-40d0-43ef-84c3-d550c4ab754f

**Comment by dhruv8433** [comment]
@Satyam1923 

now please check and inform me if it still not found...
because in local it working properly

**Comment by dhruv8433** [comment]
@Satyam1923 

kindly please check it and merge it

**Comment by Satyam1923** [comment]
@dhruv8433 still it's not working for liked button.

**Comment by dhruv8433** [comment]
@Satyam1923 

I don't know why it is not working but in local it worked properly

**Comment by dhruv8433** [comment]
@Satyam1923 

please check this and merge it

**Comment by Satyam1923** [comment]
@Satyam1923 It's not deploying properly how will I merge it. Fist pull new changes then make your issue fixes.

**Comment by dhruv8433** [comment]
@Satyam1923 

please check and inform me if it still not working

**Comment by Satyam1923** [comment]
@dhruv8433 ya still not working.

**Comment by dhruv8433** [comment]
Ok i will check that

**Comment by dhruv8433** [comment]
@Satyam1923 

now you can check this

**Comment by Satyam1923** [comment]
Screenshot 2024-06-15 234653
fix these errors.

**Comment by dhruv8433** [comment]
Ok

**Comment by Satyam1923** [comment]
@dhruv8433 did you pull new changes?

**Comment by dhruv8433** [comment]
@Satyam1923 

Yeah i pulled new changes 
I will solve deploy errors till tommorrow

**Comment by dhruv8433** [comment]
@Satyam1923 

now you can merge it
i resolve all deployment errors

**Comment by dhruv8433** [comment]
@Satyam1923 

Now you can check this and merge it

**Comment by dhruv8433** [comment]
@Satyam1923 

Please merge this

**Comment by Satyam1923** [comment]
Screenshot 2024-06-18 101712
errors.

**Comment by dhruv8433** [comment]
@Satyam1923 

please now you can check this and merge it

**Comment by Satyam1923** [comment]
Screenshot 2024-06-20 175810
use musicplayer component forthis which is already created.

**Comment by Satyam1923** [comment]
Screenshot 2024-06-20 175814
why mutlitple same things

**Comment by dhruv8433** [comment]
@Satyam1923 

image

as you say i used musiccard component and update navbar repeated icon

**Comment by dhruv8433** [comment]
please check this and merge it so i can make new pr

**Comment by dhruv8433** [comment]
@Satyam1923 

image

as you say i used musiccard component and update navbar repeated icon

**Comment by dhruv8433** [comment]
@Satyam1923 

please check this and merge it

**Comment by Satyam1923** [comment]
Screenshot 2024-06-22 003251
heart and like both are same use any one of them.

**Comment by dhruv8433** [comment]
@Satyam1923 

image

now you can merge it

**Comment by dhruv8433** [comment]
@Satyam1923 

Please merge this so i can make another pr

**Pull request merged**
