### PR TITLE
responsiveness

### LINKED ISSUE #272: Feat:Make Home Page mobile Responsive
### Describe the feature

The home page of the Spring project needs to be made responsive to ensure it displays correctly on various devices, including mobile phones, tablets, and desktops. The current layout does not adapt well to different screen sizes, affecting the user experience.

### Add ScreenShots

spring_mobile_view

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Skb08**
### Description
responsiveness on desktop,tablet and mobile view
- This PR does the following:

  - Fixes Responsiveness of the website

### Related Issues
- Placeholder: "Fixes #272 "

### Screenshots (if applicable)

https://github.com/Satyam1923/Spring-Music-Player/assets/113046759/ceda30a2-187d-4f8b-9d19-e5cffcc33f69

### Checklist
Make sure to check off all the items before submitting. Mark with [x] if done.
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings
- [X] I am working on this issue under GSSOC

### CODE REVIEW

**Comment by Satyam1923** [comment]
@Skb08 you changed the side bar for normal page also and see to it that sidebar follows the theme color not some different color and reduce the spacing between the elements for mobile design.

**Comment by Skb08** [comment]
@Satyam1923 bro this task needs a complete overhaul of the sidebar and many code updates, which will take more time to complete. Therefore, it should be categorized as level 3.

**Comment by Satyam1923** [comment]
@Skb08 then why do I observe some code updates. I can increase to level2 based on you work and effort but not level 3.

**Comment by Skb08** [comment]
ok, I will do that.
I mistakenly wrote level 3. I meant to ask you to increase it to level 2

**Comment by Satyam1923** [comment]
@Skb08 I also don't care about points and stuff but I need to keep in mind about guidelines provided by GSSoC'24.

**Comment by Skb08** [comment]
so I need to change the colour and spacing for mobile

**Comment by Skb08** [comment]
mobile_final

**Comment by Satyam1923** [comment]
@Skb08 seems good see to it only happens for mobile or tablet devices not for normal laptop size.

**Comment by Skb08** [comment]
### for labtop view it's look nice
labtop_final

**Comment by Satyam1923** [comment]
@Skb08 Ya but there's some design that everyone needs to cooperate I can't change my design according to everyone.

**Comment by Skb08** [comment]
Ok,Can you check this please
labTop

**Comment by Satyam1923** [comment]
Screenshot 2024-06-08 040759
Screenshot 2024-06-08 040805
1. bug is there 
2. don't change the design for laptop size.

**Comment by Skb08** [comment]
Now it; 's working I think

https://github.com/Satyam1923/Spring-Music-Player/assets/113046759/fd1efab9-c29d-441f-8d8e-4ca54543a63c

**Comment by Satyam1923** [comment]
Screenshot 2024-06-08 234846
Screenshot 2024-06-08 234831
breaking for both the size.

**Pull request closed without merging**
