### PR TITLE
re-designed-sidebar-#212

### LINKED ISSUE #212: Sidebar redesign
### Describe the feature

Re-designing the sidebar as shown in Figma, keeping icons only and giving the option to expand it, too. Adding hover effects on elements.

### Add ScreenShots

image

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Annu117**
### Description
A clear and concise description of what the PR does.
- This PR does the following:
  - Improved design of the sidebar added many features.

### Related Issues
- Fixes #212 

### Changes
List the detailed changes made in this PR.
- Improved design of the sidebar handed many hovering effects.
- Made it dynamic; users can add a playlist or delete or rename an existing playlist.
- Expandable sidebar

### Testing Instructions
Detailed instructions on how to test the changes. Include any setup needed and specific test cases.
1. Pull this branch.
2. Run `npm install` to install dependencies.
3. Run `npm test` to execute the test suite.
4. Verify that ...

### Screenshots (if applicable)
https://github.com/Satyam1923/Spring-Music-Player/assets/108427028/23732bcf-0cfd-4dca-92bc-8c880bf789c8

### Additional Context
Any additional context or information that reviewers should be aware of.
- This PR is based on the following...

### Checklist
Make sure to check off all the items before submitting. Mark with [x] if done.
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings
- [X] I am working on this issue under GSSOC

### CODE REVIEW

**Comment by Annu117** [comment]
@Satyam1923 updated in the new changes made. Please review it and let me know if something not looking good. 
Also, the home and search icons on expanding didn't match. Grouping is done based on the functionality.

**Comment by Annu117** [comment]
Not a copy of Spotify.

**Comment by Annu117** [comment]
ok give me permission. Check mail.

**Comment by Annu117** [comment]
One more thing. When assigning any particular task, ensure it is specific and does not change all the files, creating conflict. Just assign partwise. If someone wants to work on the home page, then in that only. Please do not assign overall page changes.

Also, keep deployment public so we can preview and resolve deployment conflicts.

**Comment by Satyam1923** [comment]
@Annu117 deployment preview is on I just need to approve it every-time. Make a copy of design file and send me the link This time around I won't give direct permissions to main design.

**Comment by Annu117** [comment]
https://www.figma.com/design/toaHGYW6wK2Yq4sKkXGIbm/Spring-Music-player-new-design-(Copy)?node-id=0-1&t=dOguCCDHa6ndKSeN-1

**Comment by Annu117** [comment]
@Satyam1923 plz check Figma and deployment.

**Comment by Satyam1923** [comment]
@Annu117 could you fix the alignment and size of all block rest it look good.

**Comment by Satyam1923** [comment]
@Annu117 I made the necessary changes in the main figma file. Take a look to it and don't use any icons tell me or check group I'll provide the resources for the icons pack.

**Comment by Annu117** [comment]
which group? I am facing an issue connecting on Discord; it says invalid. 
Where is this icon taken from? Can't find in react icons.
image

**Comment by Annu117** [comment]
https://github.com/Satyam1923/Spring-Music-Player/assets/108427028/d59f07b0-b3a0-4fe2-ad84-157fe20e61c6

**Comment by Satyam1923** [comment]
> which group? I am facing an issue connecting on Discord; it says invalid. Where is this icon taken from? Can't find in react icons. image

https://www.iconfinder.com/search?designer=fluent-designsystem&q=albums here

**Comment by Annu117** [comment]
There are 2 searchbars. The styling of the search bar is written in the App.css too, which overrides sidebar.css. 
Even if I resolve the conflict, it will be affected if someone changes in App.css.

Why is App.css made large? For new files, it will show conflicts if the class name is the same as App.css class names as parent overrides.

**Comment by Satyam1923** [comment]
@Annu117 it's not made large initially people implemented everything in app.jsx and app.css. Now it's been spited in components.

**Comment by Annu117** [comment]
plz tell them to create folders within keep .jsx and .css files. Otherwise, there will be merging conflicts.

**Comment by Annu117** [comment]
I am done. Can't find a way to attach icon provided by u. Please use react icons or easy importable icons.

**Comment by Satyam1923** [comment]
@Annu117 thank you for your effort and tolerance.

**Comment by Annu117** [comment]
See, again, it happened. I corrected the search bar icon. It's looking aligned in my system. But after someone made changes. Again, the alignment issue arose.

**Comment by Annu117** [comment]
Delete and plus icon, were hidden in latest update downloaded by me but updates done in between made them visible again.

And this issue may arise again so plz suggest them to work on limited files. Multiple changes in the same file will raise more conflicts.

**Pull request merged**
