### PR TITLE
signup form

### PR DESCRIPTION
**Pull request by siddhant-2002**
### Description
A clear and concise description of what the PR does.
- This PR does the following:
  - Adds ...
  - Fixes ...
  - Updates ...

### Related Issues
Link any related issues using the format `Fixes #issue_number`. 
This helps to automatically close related issues when the PR is merged.
- Placeholder: "Fixes #123"

### Changes
List the detailed changes made in this PR.
- Added a new feature to ...
- Refactored the ...
- Fixed a bug in ...

### Testing Instructions
Detailed instructions on how to test the changes. Include any setup needed and specific test cases.
1. Pull this branch.
2. Run `npm install` to install dependencies.
3. Run `npm test` to execute the test suite.
4. Verify that ...

### Screenshots (if applicable)
Add any screenshots that help explain or visualize the changes.

### Additional Context
Any additional context or information that reviewers should be aware of.
- This PR is based on the following...

### Checklist
Make sure to check off all the items before submitting. Mark with [x] if done.
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I am working on this issue under GSSOC

### CODE REVIEW

**Comment by siddhant-2002** [comment]
hey @Satyam1923 merge pr as soon as possible

**Comment by Satyam1923** [comment]
Screenshot 2024-07-19 201052
when fix these?
Screenshot 2024-07-19 201057

**Comment by siddhant-2002** [comment]
https://github.com/user-attachments/assets/58cd3d99-944d-4e35-917c-e5f31c20ee4f

bro its already responsive then also I have removed hardcore width see and review again

**Comment by siddhant-2002** [comment]
how much time ?

**Comment by siddhant-2002** [comment]
hey @Satyam1923 any updated i have created request long ago whats the issue

**Comment by Satyam1923** [comment]
Screenshot 2024-07-26 142635 
Screenshot 2024-07-26 142641
still same issue in my 1080p display

**Pull request closed without merging**
