### PR TITLE
#fixed: issue No. 458

### LINKED ISSUE #458: Feat:Adding a scroll-to-top button
### Describe the feature

Please add a "Scroll to Top" button to improve user experience. The button should appear after scrolling down and allow users to quickly return to the top of the page.

### Add ScreenShots

Screenshot (863)
Assign this issue  under Gssoc24.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by AnkitLuhar**
###Description

A clear and concise description of what the PR does.

This PR does the following:

1. Adds a scroll-to-top button in the footer component to enhance user interaction.

2.Fixes the visibility issue by making the button only appear when the user scrolls down the page.

3.Updates the footer component to include the new feature.

###Related Issues:

Fixes #458

###Changes:

List the detailed changes made in this PR.

1.Added a new feature to show a scroll-to-top button.

2.Refactored the footer component to include the new button.

3.Implemented the functionality to show/hide the button based on the scroll position.

###Testing Instructions:
Detailed instructions on how to test the changes. Include any setup needed and specific test cases.

1.Pull this branch.
2.Run npm install to install dependencies.
3.Run npm start to launch the application.
4.setup the frontend and backend according to it.
5.Verify that the scroll-to-top button appears when scrolling down and hides when scrolling up.
6.Click the button to ensure it scrolls the page to the top smoothly.

###Screenshots (if applicable)
[screen-capture (4).webm](https://github.com/Satyam1923/Spring-Music-Player/assets/142730608/d416bc88-8055-42c1-9552-461c0d51df52)

###Additional Context

This PR is based on the need to improve user interaction by providing an easy way to navigate to the top of the page

### CODE REVIEW

**Comment by Satyam1923** [comment]
fine just make it look good,

**Comment by AnkitLuhar** [comment]
@Satyam1923 ohk

**Comment by AnkitLuhar** [comment]
@Satyam1923 changes are made in the scroll-to-top button and also gives a little bit animation,
Attaching the file  go through it....
[screen-capture (5).webm](https://github.com/Satyam1923/Spring-Music-Player/assets/142730608/f319aa0e-d2c5-4271-abbf-9472a2a2f283)

**Comment by Satyam1923** [comment]
@AnkitLuhar change that arrow logo use something good and why yellow color? use some design which matches with ui.

**Comment by AnkitLuhar** [comment]
@Satyam1923 attaching the screenshot you can check it out then if it is okay then i will commit the changes,if the logo or the color combination you don't like it just provide me the color combination then i will do the changes according to your preferences...
Screenshot (867)

**Comment by AnkitLuhar** [comment]
@Satyam1923 done,

**Comment by AnkitLuhar** [comment]
@Satyam1923 kindly merge the PR

**Comment by AnkitLuhar** [comment]
@saurabhsingh720 please merge this PR

**Comment by AnkitLuhar** [comment]
@Satyam1923 kindly merge the PR!

**Pull request closed without merging**
