### PR TITLE
[BUG]:- Fixed the mobile view

### LINKED ISSUE #53: BUG: The app is getting break in responsiveness
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Description:- The app is breaking on checking on mobile view.

Screenshots:-
image

I want to work on this issue.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by mohit-bhandari45**
fixes #53

Description:- The mobile version of the app was messed up, so I fixed it at every different level of screen size.

Screenshots:-
image
image

### CODE REVIEW

**Review by Satyam1923 — COMMENTED** [review]
Screenshot 2024-05-13 024947
it breaks for these values.

**Comment by mohit-bhandari45** [comment]
which one?

**Comment by Satyam1923** [comment]
@mohit-bhandari45 for width 988px

**Comment by Satyam1923** [comment]
Screenshot 2024-05-13 180050
Screenshot 2024-05-13 180107
from from 1470 to 999 ui is broken.

**Comment by mohit-bhandari45** [comment]
Actually it is breaking due to height

**Comment by mohit-bhandari45** [comment]
actually some screen sizes doesn't exist, but this is responsive for most of the screen

**Comment by Satyam1923** [comment]
fine !

**Pull request merged**
