### PR TITLE
Fully updated Readme Documentation   DOC: Improvements in readme and learn documentation (Issue #74) fixed

### PR DESCRIPTION
**Pull request by SuhainaFathimaM**
Fully updated Readme Documentation
Changes Made
Updated the README.md file to enhance clarity, provide additional information, and improve the overall presentation of the Spring Music Player project repository.

Added detailed descriptions of project features, tech stack, and expected design.
Included clear instructions for setting up the backend and frontend environments.
Integrated visually appealing markdown elements, including images, links, and code snippets.
Enhanced the contributing guidelines and pull request creation process.

Please mark it as GSSoC' 24

### CODE REVIEW

**Comment by atharvakej** [comment]
image
I guess some more improvements are needed.

**Comment by SuhainaFathimaM** [comment]
@Satyam1923 Please label this PR under GSSoC

**Comment by SuhainaFathimaM** [comment]
@Satyam1923 Please label this PR under GSSoC

**Comment by SuhainaFathimaM** [comment]
@Satyam1923 I am contributing under GSSoC.. please label this PR under GSSoC

**Pull request merged**
