### PR TITLE
added login functinality from firebase

### PR DESCRIPTION
**Pull request by sadvika05**

### CODE REVIEW

**Review by sadvika05 — COMMENTED** [review]
i have added login functionality with email password authentication

**Comment by Satyam1923** [comment]
Screenshot 2024-05-10 130930
I can see that you still have removed the credentials like API key from server.js.
That is why i cannot merge it to main branch.

**Comment by sadvika05** [comment]
@Satyam1923 
do you want me to remove the sensitive information such as API key credential from server.js?

**Comment by sadvika05** [comment]
and also should i also make the login.ejs file?

**Comment by sadvika05** [comment]
@Satyam1923 okay i'll try to do it with .env file
should i also make login.ejs file?

**Comment by Satyam1923** [comment]
for now just make a basic login.ejs. After that we can start with react , which I have already you that

**Comment by Satyam1923** [comment]
Since any contribution before today's evening is null and void for points you should wait for some time

**Comment by sadvika05** [comment]
sure I'll do that and commit the changes again.

**Comment by Satyam1923** [comment]
we follow a structured approach where pull requests are initiated after mentors are assigned. Currently, we're awaiting the routes directly from GSSoC. Once we have our mentors on board, we'll proceed with raising a new pull request.

**Comment by Satyam1923** [comment]
instructed.

**Comment by Satyam1923** [comment]
instructed.

**Pull request closed without merging**
