### PR TITLE
Implemented home page design

### LINKED ISSUE #220: Implement Home page
Hey @Satyam1923,
I would like to work on the home page implementation as in the new design.

Can you assign this to me?

### PR DESCRIPTION
**Pull request by The-Phoenics**
### Description
A clear and concise description of what the PR does.
- This PR does the following:
  - Adds new Home page component
  - Implements new UI design

### Related Issues
"Fixes #220"

### Screenshots (if applicable)
homepage
homepagesmallsize

### Checklist
Make sure to check off all the items before submitting. Mark with [x] if done.
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I am working on this issue under GSSOC

### CODE REVIEW

**Comment by The-Phoenics** [comment]
Hey @Satyam1923,
I've implemented the new home page design. Can you review my PR?

**Comment by Satyam1923** [comment]
@The-Phoenics once check your deployed part.

**Comment by The-Phoenics** [comment]
Hey @Satyam1923
I only implemented the `Home` page component, didn't integrate backend search to it. So I thought showing the blank home page would not be a good idea right now and didn't add it to `App.jsx`

**Comment by Satyam1923** [comment]
@The-Phoenics so how should I test it out. Seems fine though.

**Comment by The-Phoenics** [comment]
I can add a key press event to swap between current UI and new `Home` component for testing purpose. @Satyam1923

**Comment by Satyam1923** [comment]
ya later on we can merge it once it is completed.

**Comment by The-Phoenics** [comment]
Hey @Satyam1923,
Now you can toggle the UI with pressing the ``` (tilde) key.

**Pull request merged**
