### PR TITLE
updated recently played tile ui

### LINKED ISSUE #436: Feat: UI of recently played tiles
### Describe the feature

want to improve ui of recently played tiles

### Add ScreenShots

image

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by rohit-yadavv**
### Description
- This PR Fixes the ui of recently played tile

Fixes #436 
 

image### Additional Context

### Checklist
Make sure to check off all the items before submitting. Mark with [x] if done.
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I am working on this issue under GSSOC

### CODE REVIEW

**Comment by Satyam1923** [comment]
@rohit-yadavv could you reduce the size of tile it looks different than others.

**Review by rohit-yadavv — COMMENTED** [review]
reduced size of tile

**Comment by rohit-yadavv** [comment]
image

**Comment by Satyam1923** [comment]
@rohit-yadavv at one more layer of it.

**Comment by rohit-yadavv** [comment]
image

**Comment by Satyam1923** [comment]
@rohit-yadavv would you like to work on showing real time recent played song with help of firebase?

**Comment by rohit-yadavv** [comment]
@Satyam1923 yes, i would you like to work on showing real time recent played song with help of firebase?

@Satyam1923 can you mark its label as level3 as it would be a complex task

**Comment by Satyam1923** [comment]
@rohit-yadavv ya fine i'll mark it.

**Comment by Satyam1923** [comment]
Screenshot 2024-07-02 181406
Screenshot 2024-07-02 181354
firestore schema

**Comment by rohit-yadavv** [comment]
@Satyam1923 how to access the db

**Comment by rohit-yadavv** [comment]
@Satyam1923 songIds in user schema are recent played ?

**Comment by rohit-yadavv** [comment]
@Satyam1923 merge these pr now i think it is completed now

**Comment by rohit-yadavv** [comment]
@Satyam1923 please update and merge the pr

**Comment by Satyam1923** [comment]
Screenshot 2024-07-05 172206
UI is breaking.

**Comment by Satyam1923** [comment]
@rohit-yadavv when we are clicking on recent played song it should also play that song.

**Comment by rohit-yadavv** [comment]
@Satyam1923 ok will work on that

**Comment by rohit-yadavv** [comment]
@Satyam1923 fixed that now playing songs on click
[screen-capture (1).webm](https://github.com/Satyam1923/Spring-Music-Player/assets/126584837/4549b06f-69b1-413a-9404-6e454d62ac3c)

**Pull request merged**
