### PR TITLE
Allow users to mark songs as favorites for quick access

### PR DESCRIPTION
**Pull request by ksatya2003**
Allow users to mark songs as favorites for quick access #99

### CODE REVIEW

**Comment by ksatya2003** [comment]
@Satyam1923 in which part its failing

**Review by ksatya2003 — COMMENTED** [review]
I cant understand that..I which it shows failure

**Comment by ksatya2003** [comment]
@saurabhsingh720 please review it...

**Comment by ksatya2003** [comment]
@Satyam1923  hello plesae review it

**Comment by Satyam1923** [comment]
firstly merge new changes.

**Comment by ksatya2003** [comment]
.But my name is not in leaderboard..please help me

**Comment by ksatya2003** [comment]
@Satyam1923  please help me in this

**Comment by ksatya2003** [comment]
@saurabhsingh720  @Satyam1923  when will you merge this code?

**Comment by Satyam1923** [comment]
@ksatya2003 when will you resolve conflicts.

**Comment by ksatya2003** [comment]
@ksatya2003  ok I will rsolve conflicts ..But I dont know why these are arising

**Comment by ksatya2003** [comment]
@Satyam1923  Unexpectedly its closed please help me in this to reopen this pr

**Comment by Satyam1923** [comment]
again conflicts

**Comment by ksatya2003** [comment]
@Satyam1923  I tried to resolve conflicts but still it shows conflicts

**Comment by Satyam1923** [comment]
@ksatya2003 it might be because you are making changes then some other also makes the changes in same file. Best is to create a new component while working.

**Comment by ksatya2003** [comment]
@Satyam1923  by merging this updated code with my code resulting of errors

**Comment by Satyam1923** [comment]
@ksatya2003 yes that is the problem. Only way is to make minimal changes.

**Comment by ksatya2003** [comment]
@Satyam1923  ok i will try it

**Comment by ksatya2003** [comment]
@Satyam1923  once check this pull request

**Comment by Satyam1923** [comment]
@ksatya2003 seems fine it's breaking for top charts as soon as I click on play button it breaks.

**Comment by ksatya2003** [comment]
@Satyam1923  is it ok or to change

**Comment by Satyam1923** [comment]
@ksatya2003 ya need to fixed.

**Comment by ksatya2003** [comment]
@Satyam1923 ok

**Comment by ksatya2003** [comment]
@Satyam1923  which functionality do you want.I cant understand

**Comment by Satyam1923** [comment]
https://github.com/Satyam1923/Spring-Music-Player/assets/104068640/a0aa1d1d-52da-4723-941b-719bcb9dd8f4

this thing is breaking now I want you to fix it.

**Comment by ksatya2003** [comment]
@Satyam1923  once check it

**Comment by Satyam1923** [comment]
@ksatya2003 fine seems fine now.

**Pull request merged**
